services:
  foodium_python_backend:
    build:
      context: .
    ports:
      - 5000:5000
    depends_on:
      - redis_stack_server
  redis_stack_server:
    image: redis/redis-stack-server:latest
    volumes:
      - local-data:/data
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
volumes:
  local-data:
    driver: azure_file
    driver_opts:
      share_name: rediscache
      storage_account_name: foodiumbackend
      storage_account_key: ${STORAGE_ACCOUNT_KEY}
